GET http://localhost:8080/

###
POST http://localhost:8080/create-list
Content-Type: application/json

{
    "titulo": "Velozes e Furiosos",
    "genero": "Ação",
    "duracao": "1 Hora e 46 minutos",
    "classificacao_etaria": 14
}

###
DELETE http://localhost:8080/delete-list/1

###
GET http://localhost:8080/all-filmes/