GET http://localhost:8080/all-filmes

###

POST http://localhost:8080/create-list
Content-Type: application/json

{
    "titulo": "Como Treinar o seu Dragão 3",
    "genero": "Infantil/Fantasia",
    "duracao": "1 horas 44 minutos",
    "classificacao_etaria": 0
}

###
http://localhost:8080/edit-filme/1

{
    "titulo": "Velozes e Furiosos 2"
}

###

DELETE http://localhost:8080/delete-list/1
